apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keda-http-addon-example.fullname" . }}-nginx-config
  labels:
    {{ include "keda-http-addon-example.labels" . | nindent 4}}

data:
  {{- $files := .Files }}
  nginx.conf: |
{{- $files.Get "data/nginx.conf" | nindent 4 }}